#!/usr/bin/env python3
USERNAME = 'pengyy9918'
USERPASS = 'PYY200029'
INTERVAL = 86400 
MAX_RETRY = 30
RETRY_INTERVAL = 20
DEBUG = 0#+1

import re
from sys import argv
import json
from datetime import date
import time
import urllib3
import requests
import logging
from logging import debug, info, warning, error, critical

logging.basicConfig(level=logging.INFO,#控制台打印的日志级别
                    filename='jluhealthy_pyy.log',
                    filemode='w',##模式，有w和a，w就是写模式，每次都会重新写日志，覆盖之前的日志
                    #a是追加模式，默认如果不写的话，就是追加模式
                    format=
                    '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
                    #日志格式
                    )
def Weiserver(head,info):
        url = 'https://sc.ftqq.com/SCU92108T10d53ff8e8e08bc9a918623923d451ca5e8408e28384d.send'
        header = {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36',
        }
        data ={
                'text':head,
                'desp': info
        }
        response = requests.post(url=url,data=data,headers=header)
        print(response.json())

logging.basicConfig(level=logging.INFO-10*DEBUG, format='%(asctime)s %(levelname)s %(message)s')
warning('Started.')
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
tries = 0

while True: # main loop
	try:
		info('Authenticating...')
		tries += 1
		s = requests.Session()
		s.headers.update({'Referer':'https://ehall.jlu.edu.cn/'})
		s.verify = False
		
		r = s.get('https://ehall.jlu.edu.cn/jlu_portal/login')
		pid = re.search('(?<=name="pid" value=")[a-z0-9]{8}', r.text)[0]
		debug('PID: '+pid)

		postPayload = {'username':USERNAME,'password':USERPASS,'pid':pid}
		r = s.post('https://ehall.jlu.edu.cn/sso/login',data=postPayload)

		info('Requesting form...')
		r = s.get('https://ehall.jlu.edu.cn/infoplus/form/JLDX_BK_XNYQSB/start')
		csrfToken = re.search('(?<=csrfToken" content=").{32}',r.text)[0]
		debug('CSRF: '+csrfToken)

		postPayload = {'idc':'JLDX_BK_XNYQSB','csrfToken':csrfToken}
		r = s.post('https://ehall.jlu.edu.cn/infoplus/interface/start',data=postPayload)
		sid = re.search('(?<=form/)\\d*(?=/render)',r.text)[0]
		debug('Step ID: '+sid)

		postPayload = {'stepId':sid,'csrfToken':csrfToken}
		r = s.post('https://ehall.jlu.edu.cn/infoplus/interface/render',data=postPayload)
		data = json.loads(r.content)['entities'][0]
		payload_1 = data['data']
		payload_1['fieldCNS'] = True
		payload_1 = json.dumps(payload_1,ensure_ascii=False).replace('食品科学与工程学院','数学学院')
		# payload_1 = json.dumps(payload_1)
		info('DATA: '+payload_1)
		payload_2 = ','.join(data['fields'].keys())
		debug('FIELDS: '+payload_2)

		info('Submitting form...')
		postPayload = {
			'actionId':1,
			'formData':payload_1,
			'nextUsers':'{}',
			'stepId':sid,
			'timestamp':int(time.time()),
			'boundFields':payload_2,
			'csrfToken':csrfToken
		}
		r = s.post('https://ehall.jlu.edu.cn/infoplus/interface/doAction',data=postPayload)
		debug(r.text)

		if json.loads(r.content)['ecode'] != 'SUCCEED' :
			raise Exception('The server returned a non-successful status.')

	except Exception as e:
		warning(e)
		if tries >= MAX_RETRY :
			critical('Failed too many times! Exiting...')
			exit()
		error('Unknown error occured, retrying...')
		time.sleep(RETRY_INTERVAL)
		continue

	if len(argv) > 1 and argv[1] == '--once' :
		localtime = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
		Weiserver('jlu健康报表','sucess'+localtime)
		info('Success! Exiting...')
		exit()

	info('Success! Waiting for next run...')
	tries = 0
	time.sleep(INTERVAL)
